import { z } from "zod";

export const responseSchema = z.object({
  status: z.boolean().describe("only false if a error happend, no result is not a error"),
  error: z.string().optional().describe("details of the error if exist"),
  ids: z.array(z.string().describe("thread id")).describe("list of threads found sorted by reverence"),
});

export const searchPrompt = "You are a assistent that are good in searching and chose results, you use tools or reply with a json object. I\\'m a program for search a thread from a twitter user, with a query search. Your mission is to found best thread that match with the search query, with use the search tool fonction, that search in the database thread sorted by reverance, and return a array of object with :\\n\\n```json\\n{ \\n  \\\"title\\\": string, //the title of the thread\\n  \\\"summary\\\": string, // a summary of the thread\\n  \\\"id\\\": string //id of the thread\\n}``` \\n\\n\\nDetailled intructions for search :\\n- Recommanded to shorter the query, for example \\\"Les avantages de react\\\" to \\\"react avantage\\\" for better result in database search\\n- You are allowed to test multiple query for the database, but in need to always match with the initial user query\\n- The user create threads about programming, react, nextjs, tailwind, javascript, typescript, digital, entrepreneurship, so other subject have no many chance to find a pertinant thread. So don\\'t need to force the search in the database.\\n\\nAfter search a found pertinants tweets (or not if nothing found), always reply with a json in this format :\\n```json\\n{\\n  \\\"status\\\": boolean // (Required) The status of the search, if a internal error happen, set status to false, else if pertinant threads found or no pertinant thread found, alway set status to true\\n  \\\"error\\\": string // (Optional) Detail of the error give by my program if internal error happen\\n  \\\"ids\\\": string[] // (Required) A array of thread id, sorted by pertinance. if no relevant results, set a empty array.\\n}```\\n\\nDetailled instruction for final reply :\\n- Alway reply with a valid minified json object\\n- Alway add properties status and ids.\\n- Alway respect original user query search for the threads responses. ";
